name: Actualizar y elegir listas

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Actualizar lista1 y lista2
  actualizar_listas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Actualizar lista1
        run: |
          echo "Opción 1" >> lista1.txt
          echo "Opción 2" >> lista1.txt

      - name: Actualizar lista2
        run: |
          echo "Opción A" >> lista2.txt
          echo "Opción B" >> lista2.txt

  # Job 2: Elegir entre las opciones de lista1 y lista2
  elegir_lista:
    needs: actualizar_listas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Leer lista1 y lista2
        run: |
          echo "Selecciona entre las opciones de lista1 y lista2:"
          echo "Contenido de lista1:"
          cat lista1.txt
          echo "Contenido de lista2:"
          cat lista2.txt

      - name: Elegir opción (simulación)
        run: |
          # Simulación de elegir entre lista1 y lista2
          selected_option="Opción 1"  # Puedes cambiar esto según tu lógica
          echo "Has elegido: $selected_option"
