name: Selección Dinámica de Listas

on:
  workflow_dispatch:
    inputs:
      lista1:
        description: 'Selecciona una opción de lista1'
        required: true
        type: choice
        options:
          - "Opción 1"
          - "Opción 2"
      lista2:
        description: 'Selecciona una opción de lista2'
        required: true
        type: choice
        options:
          - "Opción A"
          - "Opción B"

jobs:
  # Job 1: Leer archivos lista1.txt y lista2.txt
  leer_archivos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Leer contenido de lista1.txt
        id: leer_lista1
        run: |
          lista1=$(cat lista1.txt)
          echo "Contenido de lista1.txt: $lista1"
          echo "::set-output name=lista1::$(echo $lista1)"

      - name: Leer contenido de lista2.txt
        id: leer_lista2
        run: |
          lista2=$(cat lista2.txt)
          echo "Contenido de lista2.txt: $lista2"
          echo "::set-output name=lista2::$(echo $lista2)"

  # Job 2: Imprimir las opciones y seleccionar
  elegir_opcion:
    runs-on: ubuntu-latest
    needs: leer_archivos
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Imprimir el contenido de lista1 y lista2
        run: |
          echo "Contenido de lista1.txt:"
          cat lista1.txt
          echo "Contenido de lista2.txt:"
          cat lista2.txt

      - name: Seleccionar opción de lista1 y lista2
        run: |
          selected_option_lista1="${{ github.event.inputs.lista1 }}"
          selected_option_lista2="${{ github.event.inputs.lista2 }}"
          echo "Has seleccionado de lista1: $selected_option_lista1"
          echo "Has seleccionado de lista2: $selected_option_lista2"
