name: Selección de listas desde archivos

on:
  workflow_dispatch:
    inputs:
      lista1:
        description: 'Selecciona una opción de lista1'
        required: true
        type: choice
        options: []  # Se llenará con el contenido de lista1.txt
      lista2:
        description: 'Selecciona una opción de lista2'
        required: true
        type: choice
        options: []  # Se llenará con el contenido de lista2.txt

jobs:
  # Job 1: Leer archivos lista1.txt y lista2.txt
  leer_archivos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Leer lista1.txt
        id: lista1
        run: |
          # Leer el contenido de lista1.txt y guardarlo en una variable
          echo "::set-output name=lista1::$(cat lista1.txt)"

      - name: Leer lista2.txt
        id: lista2
        run: |
          # Leer el contenido de lista2.txt y guardarlo en una variable
          echo "::set-output name=lista2::$(cat lista2.txt)"

  # Job 2: Seleccionar una opción
  seleccionar_opcion:
    needs: leer_archivos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Imprimir las opciones de lista1 y lista2
        run: |
          echo "Contenido de lista1.txt:"
          cat lista1.txt
          echo "Contenido de lista2.txt:"
          cat lista2.txt

      - name: Crear entradas de selección (simulación)
        run: |
          # Este paso es solo una simulación de lo que ocurriría si los inputs se llenaran dinámicamente
          echo "Seleccionando una opción de lista1: ${{ github.event.inputs.lista1 }}"
          echo "Seleccionando una opción de lista2: ${{ github.event.inputs.lista2 }}"
